import type { Source } from '@/types'

interface ExportPayload {
  title: string
  report: string
  feedback?: string
  score?: number | null
  sources?: Source[]
  createdAt?: number
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  // Revoke on the next tick so the download has certainly started.
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export function slugify(text: string): string {
  return (
    text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'research-report'
  )
}

/** The canonical text form; every other export is derived from this. */
export function toMarkdown({ title, report, feedback, score, sources, createdAt }: ExportPayload): string {
  const date = new Date(createdAt ?? Date.now()).toISOString().slice(0, 10)
  const parts = [`# ${title}`, '', `_Generated by Multi-Agent AI Research on ${date}_`, '', report]

  if (sources?.length) {
    parts.push('', '## References', '')
    sources.forEach((source, index) => {
      parts.push(`${index + 1}. [${source.title || source.url}](${source.url})`)
    })
  }

  if (feedback) {
    parts.push('', '---', '', '## Critic Review', '')
    if (score != null) parts.push(`**Score:** ${score}/10`, '')
    parts.push(feedback)
  }

  return parts.join('\n')
}

export function exportMarkdown(payload: ExportPayload) {
  download(new Blob([toMarkdown(payload)], { type: 'text/markdown;charset=utf-8' }), `${slugify(payload.title)}.md`)
}

/**
 * A .doc file that is really styled HTML — Word and Google Docs both open it,
 * and it needs no dependency. Markdown is converted with a minimal renderer
 * because the payload only ever contains the headings/lists/emphasis the
 * writer prompt asks for.
 */
export function exportWord(payload: ExportPayload) {
  const body = markdownToHtml(toMarkdown(payload))
  const html = `<!DOCTYPE html><html xmlns:w="urn:schemas-microsoft-com:office:word"><head>
<meta charset="utf-8"><title>${escapeHtml(payload.title)}</title>
<style>
  body { font-family: Calibri, sans-serif; font-size: 11pt; line-height: 1.6; color: #1a1a1a; }
  h1 { font-size: 22pt; } h2 { font-size: 16pt; } h3 { font-size: 13pt; }
  a { color: #1a56db; } hr { border: none; border-top: 1px solid #ddd; }
  code { font-family: Consolas, monospace; background: #f3f3f3; padding: 1px 4px; }
</style></head><body>${body}</body></html>`
  download(new Blob([html], { type: 'application/msword' }), `${slugify(payload.title)}.doc`)
}

/**
 * PDF via the browser's own print pipeline.
 *
 * Bundling a PDF engine would add hundreds of KB to render a text document the
 * print dialog already handles well — and the print path gets the user's page
 * size and margins for free. The window is opened and driven synchronously so
 * popup blockers treat it as user-initiated.
 */
export function exportPdf(payload: ExportPayload) {
  const body = markdownToHtml(toMarkdown(payload))
  const frame = document.createElement('iframe')
  frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;'
  document.body.appendChild(frame)

  const doc = frame.contentDocument
  if (!doc) {
    frame.remove()
    return
  }

  doc.open()
  doc.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(payload.title)}</title>
<style>
  @page { margin: 20mm; }
  body { font-family: -apple-system, Segoe UI, sans-serif; font-size: 11pt; line-height: 1.65; color: #111; }
  h1 { font-size: 24pt; margin-bottom: 4pt; } h2 { font-size: 15pt; margin-top: 18pt; }
  h3 { font-size: 12pt; } a { color: #1a56db; text-decoration: none; word-break: break-all; }
  hr { border: none; border-top: 1px solid #ddd; margin: 18pt 0; }
  code { font-family: ui-monospace, Consolas, monospace; background: #f4f4f5; padding: 1px 4px; border-radius: 3px; }
  pre { background: #f4f4f5; padding: 10pt; border-radius: 4pt; overflow-x: auto; }
  li { margin-bottom: 4pt; }
</style></head><body>${body}</body></html>`)
  doc.close()

  frame.contentWindow?.focus()
  frame.contentWindow?.print()
  // Keep the frame alive long enough for the print dialog to read it.
  setTimeout(() => frame.remove(), 60_000)
}

function escapeHtml(text: string): string {
  return text.replace(/[&<>"]/g, (char) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[char] ?? char,
  )
}

/**
 * Deliberately small markdown -> HTML converter for the export path only.
 * On-screen rendering goes through react-markdown; this exists so the export
 * helpers stay dependency-free and synchronous.
 */
function markdownToHtml(markdown: string): string {
  const lines = markdown.split('\n')
  const html: string[] = []
  let inList = false
  let inCode = false

  const closeList = () => {
    if (inList) {
      html.push('</ul>')
      inList = false
    }
  }

  for (const line of lines) {
    if (line.trim().startsWith('```')) {
      closeList()
      html.push(inCode ? '</pre>' : '<pre>')
      inCode = !inCode
      continue
    }
    if (inCode) {
      html.push(escapeHtml(line))
      continue
    }

    const heading = /^(#{1,6})\s+(.*)$/.exec(line)
    if (heading) {
      closeList()
      const level = heading[1].length
      html.push(`<h${level}>${inline(heading[2])}</h${level}>`)
      continue
    }

    if (/^---+$/.test(line.trim())) {
      closeList()
      html.push('<hr>')
      continue
    }

    const bullet = /^\s*[-*]\s+(.*)$/.exec(line)
    if (bullet) {
      if (!inList) {
        html.push('<ul>')
        inList = true
      }
      html.push(`<li>${inline(bullet[1])}</li>`)
      continue
    }

    const numbered = /^\s*\d+\.\s+(.*)$/.exec(line)
    if (numbered) {
      if (!inList) {
        html.push('<ul>')
        inList = true
      }
      html.push(`<li>${inline(numbered[1])}</li>`)
      continue
    }

    closeList()
    if (line.trim()) html.push(`<p>${inline(line)}</p>`)
  }

  closeList()
  if (inCode) html.push('</pre>')
  return html.join('\n')
}

function inline(text: string): string {
  return escapeHtml(text)
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/(^|[^*])\*([^*]+)\*/g, '$1<em>$2</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    // Bare URLs left over from the pipeline's source extraction.
    .replace(/(^|\s)(https?:\/\/[^\s<]+)/g, '$1<a href="$2">$2</a>')
}
